version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    ports:
      - '4563-4599:4563-4599'
      - '9080:8080'
    environment:
      - SERVICES=sqs
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'